### ISSUE TITLE
Annotation limit is failing PRs

### ISSUE THREAD

**Issue by imsteev** [bradennapier/eslint-plus-action#18]
Got this error as a result of having a project with many existing ESLint warnings:
```
No more than 50 items are allowed; 295 were supplied.
##[error]Invalid request.
```

Is it possible to expose an option that can customize this limit? Or even simpler, just allow all annotations to go through by default?

**Comment by bradennapier** [comment]
Lots of issues you had in your changed files eh? :-D

**Comment by bradennapier** [comment]
@imsteev - can you try `bradennapier/eslint-plus-action@beta` and let me know if that works for you?

**Comment by imsteev** [comment]
@bradennapier it worked! (had to prefix the version with `"v"`, e.g `bradennapier/eslint-plus-action@v3.4.0`)

**Comment by bradennapier** [comment]
Ah yes, my bad.  Good to hear it worked though.  I didn't really test it with so many annotations :).
