### ISSUE TITLE
annotateWarnings doesn't work

### ISSUE THREAD

**Issue by imsteev** [bradennapier/eslint-plus-action#29]
the annotateWarnings configuration option doesn't seem to be working. has it been implemented?

@bradennapier

**Comment by imsteev** [comment]
i think it has the wrong name
```
  reportWarnings:
    description: 'By setting this to "false", only errors will be annotated'
    required: false
```

**Comment by bradennapier** [comment]
Yes, sorry - renamed that recently.

**Comment by imsteev** [comment]
thank you!

**Comment by Zodiase** [comment]
FYI, https://github.com/bradennapier/eslint-plus-action/blame/master/README.md#L80 still says `annotateWarnings`.
