### ISSUE TITLE
Action using deprecated CLIEngine

### ISSUE THREAD

**Issue by WildCard65** [bradennapier/eslint-plus-action#46]
As of ESLint 7.0, ```CLIEngine``` is deprecated in favour of ```ESLint```

**Comment by bradennapier** [comment]
Is the command not working for you?  ESLint did not implement the necessary features and when i asked the eslint team they told me to use CLIEngine.

As of when i built this, ESLint used CLIEngine itself.

**Comment by WildCard65** [comment]
For the most part, yes.
It's not generating annotations nor any reports of ignored files.

**Comment by WildCard65** [comment]
@bradennapier Deleted my other comment, just figured out I needed "@typescript-eslint/parser"
