### ISSUE TITLE
Workflow appears twice

### ISSUE THREAD

**Issue by michaelaflores** [bradennapier/eslint-plus-action#51]
I'm not sure if this is actually related to the workflow or due to my own setup, but I noticed the workflow appears twice in the workflow list. One of those instances appears nested under an unrelated workflow. Do you happen to know how to fix this? 

<img width="343" alt="Screen Shot 2020-10-20 at 10 22 44 AM" src="https://user-images.githubusercontent.com/11711706/96607929-74f17700-12be-11eb-99a2-9987ab2abd4a.png">

**Comment by bradennapier** [comment]
This is because it creates a new workflow in the workflow which holds the results themselves (and annotations).  I believe this is as recommended for producing annotations.

**Comment by michaelaflores** [comment]
@bradennapier makes sense!
